[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = [
  "npm ci --prefix server",
  "npm ci --prefix client"
]

[phases.build]
cmds = [
  "npm run build --prefix client"
]

[start]
cmd = "npm start --prefix server"

